import AuthProvider from "@/components/next-auth/AuthProvider";
import "./globals.css";
import { Hind_Siliguri } from "next/font/google";
import TopLoader from "@/components/sub-components/TopLoader";

const HindSiliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Buy Sell Project - TeamSaroar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={HindSiliguri.className}>
        <TopLoader />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
