import UserNavServerComp from "@/components/sub-components/UserNavServer";
import UserSidebar from "@/components/sub-components/UserSidebar";

export const metadata = {
  title: "Super Admin - Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <div className="grid grid-cols-12"></div>
    </>
  );
}
